version: "3.1"
services:
  php5:
    build:
      context: docker/apache_php
    container_name: yii_app_php
    links:
      - db
      - phpmyadmin
    ports:
      - "81:80"
    volumes:
      - .:/var/www/project
      - ~/.composer/auth.json:/root/.composer/auth.json
      
  db:
    build:
      context: docker/db
    container_name: yii_app_db
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=databasename
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      ports:
        - "8081:80"